language: rust
env:
  global:
    - secure: CypapAJnmOcE+/5uf2ad944IfJwD20whIIsbG+6nNjP34JDJ6EonP4+TuPFLTtZ4PPe2sUAI39TO97gwna2zOJEtU9qeNigvT9yQnDnvr6jkb4QzNJ6lOd42uwHUPvzD9vSjlGLpbAo2PUq8IKw52ehZtN5KvTLyehSoAc2eO6U=
script:
    - cargo build
    - cargo test
    - cargo doc
after_script:
  # the doc directory needs to be in the root for rust-ci
  - mv target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh

