language: rust
env:
  global:
    - secure: CypapAJnmOcE+/5uf2ad944IfJwD20whIIsbG+6nNjP34JDJ6EonP4+TuPFLTtZ4PPe2sUAI39TO97gwna2zOJEtU9qeNigvT9yQnDnvr6jkb4QzNJ6lOd42uwHUPvzD9vSjlGLpbAo2PUq8IKw52ehZtN5KvTLyehSoAc2eO6U=
install:
    - sudo apt-get install libXxf86vm-dev xdotool
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - cmake -DCMAKE_C_FLAGS=-fPIC -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
    - make
    - sudo make install
    - cd ..
script:
    - cargo build
    - cargo test
    - cargo doc
    - cp -r target/doc doc
    - cd src/example
    - cargo build
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
