[package]
name = "example"
version = "0.1.0"
authors = [
    "Colin Sherratt <colin.sherratt@gmail.com>",
]

[[bin]]
name = "example"
path = "main.rs"

[dependencies.genmesh]
path = "../../"

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d.git"